CREATE TABLE ROOM
(
    ROOM_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(16) NOT NULL,
    ROOM_NUMBER CHAR(2)     NOT NULL UNIQUE,
    BED_INFO    CHAR(2)     NOT NULL
);

CREATE TABLE GUEST
(
    GUEST_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME    VARCHAR(64),
    LAST_NAME     VARCHAR(64),
    EMAIL_ADDRESS VARCHAR(64),
    ADDRESS       VARCHAR(64),
    COUNTRY       VARCHAR(32),
    STATE         VARCHAR(12),
    PHONE_NUMBER  VARCHAR(24)
);

CREATE TABLE RESERVATION
(
    RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID        BIGINT NOT NULL,
    GUEST_ID       BIGINT NOT NULL,
    RES_DATE       DATE
);

CREATE TABLE USER
(
    USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE AUTH_USER_GROUP
(
    AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME           VARCHAR(128) NOT NULL,
    AUTH_GROUP         VARCHAR(128) NOT NULL,
    CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME),
    UNIQUE (USERNAME, AUTH_GROUP)
);

ALTER TABLE RESERVATION
    ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID);
ALTER TABLE RESERVATION
    ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST (GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION (RES_DATE);
